name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-tests:
    runs-on: ubuntu-latest

    env:
      MYSQL_ROOT_PASSWORD: root

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up PHP environment
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Use the PHP version required for your project
        extensions: pdo_mysql # Add any PHP extensions you need

    # Step 3: Install dependencies
    - name: Install Composer Dependencies
      run: composer install --no-dev --prefer-dist

    # Step 4: Start a MySQL database service
    - name: Start MySQL service
      run: |
        sudo service mysql start
        mysql -u root -p$MYSQL_ROOT_PASSWORD -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '$MYSQL_ROOT_PASSWORD'; FLUSH PRIVILEGES;"
        mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE cat_kery;"
        mysql -u root -p$MYSQL_ROOT_PASSWORD cat_kery < ./cat-kery.sql # Import your database schema if needed

    # Step 5: Run PHPUnit Tests
    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit

    # Step 6: Archive Test Results (Optional)
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./tests/
