name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-tests:
    runs-on: ubuntu-latest

    env:
      MYSQL_ROOT_PASSWORD: root
      SERVER_PORT: 8000

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up PHP environment
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: pdo_mysql

    # Step 3: Configure and Start MySQL
    - name: Start MySQL service
      run: |
        sudo service mysql start
        mysql -u root -p$MYSQL_ROOT_PASSWORD -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION';"
        mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS cat_kery;"
        mysql -u root -p$MYSQL_ROOT_PASSWORD cat_kery < ./cat-kery.sql

    # Step 4: Install Composer Dependencies
    - name: Install Composer Dependencies
      run: |
        rm -rf vendor
        composer install --prefer-dist

    # Step 5: Start PHP Web Server
    - name: Start PHP Web Server
      run: |
        php -S localhost:$SERVER_PORT -t ./cat-kery > server.log 2>&1 &
    
    # Debugging Steps
    - name: Debug Running Processes
      run: ps aux | grep php

    - name: Debug PHP Server Logs
      run: cat server.log

    - name: Check Port Availability
      run: sudo netstat -tuln | grep :$SERVER_PORT || echo "Port is available"

    # Step 6: Verify Server Accessibility
    - name: Test Application Accessibility
      run: curl -v http://localhost:$SERVER_PORT/

    # Step 7: Run PHPUnit Tests
    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit --testdox
