name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-tests:
    runs-on: ubuntu-latest

    env:
      MYSQL_ROOT_PASSWORD: root

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up PHP environment
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: pdo_mysql

    # Step 3: Configure and Start MySQL
    - name: Start MySQL service
      run: |
        sudo service mysql start
        mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE cat_kery;"
        mysql -u root -p$MYSQL_ROOT_PASSWORD cat_kery < ./cat-kery.sql

    # Step 4: Install Composer Dependencies
    - name: Install Composer Dependencies
      run: |
        composer clear-cache
        rm -rf vendor
        composer install --prefer-dist

    # Step 5: Verify Application Is Accessible
    - name: Test Application Accessibility
      run: curl http://localhost/cat-kery/

    # Step 6: Run PHPUnit Tests
    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit
